- name: Install and configure WordPress
  hosts: all
  become: true
  vars:
    db_name: wordpress_db
    db_user: wp_user
    db_password: wp_password
    wp_admin_user: admin
    wp_admin_password: admin_password
    wp_site_title: "Example WordPress Site"
    wp_site_url: "example.com"
  tasks:
    - name: Install packages required for WordPress
      package:
        name:
        - apache2
        - mysql-server
        - php-mysql
        - php
        - libapache2-mod-php
        - python3-mysqldb
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install packages required for WordPress
      package:
        name:
          - httpd
          - php
          - mysql-community-server
          - php-mysqlnd
          - php-mbstring
          - MySQL-pythons
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: true
      when: ansible_os_family == 'Debian'

    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_os_family == 'RedHat'

    - name: Start and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: true

    - name: Create WordPress database user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        state: present

    - name: Create WordPress database
      mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Download and extract WordPress core files
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/wordpress.tar.gz
      register: download_wordpress

    - name: Extract WordPress core files
      command: "tar xzf /tmp/wordpress.tar.gz --strip-components=1 -C /var/www/html/wordpress"
      when: download_wordpress is succeeded

    - name: Set ownership of WordPress directory
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        recurse: true
  handlers:
    - name: enable apache site
      command: apache2ctl graceful
      notify:
        - reload apache
    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
      when: ansible_os_family == 'Debian'

    - name: Restart Apache service
      service:
        name: httpd
        state: restarted
      when: ansible_os_family == 'RedHat'