---
- name: Install WordPress on AWS EC2 and Azure VM
  hosts: all
  become: true
  vars:
    # WordPress settings
    wp_db_name: final_db
    wp_db_user: final_user
    wp_db_password: finaldb_password
    wp_admin_user: admin
    wp_admin_password: admin_password
    wp_site_title: "final"
    wp_site_url: "final.com"

  tasks:
    # Install required packages
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - apache2
        - php
        - php-mysql
        - mysql-server
        - mysql-client
        - python-mysqldb

    # Set up Apache virtual host
    - name: Set up Apache virtual host
      template:
        src: templates/apache-vhost.conf.j2
        dest: /etc/apache2/sites-available/{{ wp_site_url }}
      notify:
        - enable apache site
        - reload apache

    # Enable Apache virtual host
    - name: Enable Apache virtual host
      command: a2ensite {{ wp_site_url }}
      args:
        creates: /etc/apache2/sites-enabled/{{ wp_site_url }}
      notify:
        - reload apache

    # Reload Apache
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    # Set up MySQL database
    - name: Set up MySQL database
      mysql_db:
        name: "{{ wp_db_name }}"
        state: present
        login_user: root
        login_password: ""

    # Create MySQL user and grant privileges
    - name: Create MySQL user and grant privileges
      mysql_user:
        name: "{{ wp_db_user }}"
        password: "{{ wp_db_password }}"
        priv: "{{ wp_db_name }}.*:ALL"
        state: present
        login_user: root
        login_password: ""

    # Install WordPress
    - name: Install WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/wordpress.tar.gz
      register: wordpress_download

    - name: Extract WordPress archive
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: true
        creates: /var/www/html/wordpress

    - name: Set up WordPress config file
      template:
        src: templates/wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php

      handlers:
    - name: enable apache site
      command: a2ensite {{ wp_site_url }}
      args:
        creates: /etc/apache2/sites-enabled/{{ wp_site_url }}
      notify:
        - reload apache

    - name: reload apache
      service:
        name: apache2
        state: restarted
